-- 리뷰테이블 생성
CREATE TABLE REVIEW (
	IDX NUMBER PRIMARY KEY,
	TOILET_IDX NUMBER NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	SCORE NUMBER(1,1) NOT NULL,
	MAIN_TEXT VARCHAR(300),
	INSERT_DT DATE
	USER_IP CHAR(16)
);

ALTER TABLE REVIEW
ADD USER_IP CHAR(16);

-- 리뷰정보등록
INSERT INTO REVIEW (
	IDX,
	TOILET_IDX,
	NAME,
	SCORE ,
	MAIN_TEXT,
	INSERT_DT,
	USER_IP
) VALUES (
	SQ_REVIEW.NEXTVAL,
	1,
	'아무ww',
	4.1,
	'akakakakkakak',
	sysdate,
	'127.127.127.127'
);

-- 리뷰정보조회
SELECT NAME, SCORE, MAIN_TEXT, INSERT_DT, USER_IP
FROM REVIEW;

-- 리뷰정보조회
SELECT *
FROM REVIEW;

-- 화장실 인덱스로 리뷰갯수조회
SELECT COUNT(*)
FROM REVIEW
WHERE TOILET_IDX = 1;

ALTER TABLE REVIEW
MODIFY SCORE NUMBER(3, 1);

ALTER TABLE REVIEW
ADD CONSTRAINT FK_TOILET_REVIEW
FOREIGN KEY (TOILET_IDX)
REFERENCES TOILET_INFO (IDX);

CREATE SEQUENCE KM.SQ_REVIEW INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER;


-- 기본형
SELECT *
FROM TOILET_INFO TI
JOIN TOILET_DETAIL TD ON TI.IDX = TD.TOILET_IDX


-- 서브쿼리
SELECT TI.*, TD.LOCK_YN
FROM TOILET_INFO TI
JOIN ( 
	SELECT MAX(INSERT_DT) INSERT_DT, LOCK_YN, TOILET_IDX
	FROM TOILET_DETAIL
	GROUP BY TOILET_IDX, lock_yn
) TD ON TI.IDX = TD.TOILET_IDX









