-- 화장실 상세정보 테이블 생성
CREATE TABLE TOILET_DETAIL(
	IDX	NUMBER PRIMARY KEY,
	TOILET_IDX NUMBER,
	GENDER_YN CHAR(1) NOT NULL,
	LOCK_YN CHAR(1)	NOT NULL,
	PRESSURE_YN CHAR(1),
	TISSUE_YN CHAR(1),
	SOAP_YN CHAR(1),
	TOILET_CNT NUMBER,
	BIDET_YN CHAR(1),
	CLEANLINESS VARCHAR2(90),
	FACILITY VARCHAR2(150),
	INSERT_DT DATE NOT NULL,
	USER_IP CHAR(16) NOT NULL,

	CONSTRAINT FK_TOILET_TOILET_DETAIL FOREIGN KEY(TOILET_IDX)
	REFERENCES TOILET_INFO(IDX) ON DELETE CASCADE
);

-- 화장실 상세정보 등록
INSERT INTO TOILET_DETAIL(
	IDX			
	, TOILET_IDX	
	, GENDER_YN	 -- 3개로 수정
	, LOCK_YN		
	, PRESSURE_YN	
	, TISSUE_YN	
	, SOAP_YN		
	, TOILET_CNT	
	, BIDET_YN	
	, CLEANLINESS	
	, FACILITY	
	, INSERT_DT	
	, USER_IP		
) VALUES (
	SQ_TOILET_DETAIL.NEXTVAL,
	2,
	'Y',
	'Y',
	'Y',
	'Y',
	'Y',
	3,
	'Y',
	'ATEATEADSAFSDA',
	'ATEATEADSAFSDA',
	SYSDATE,
	'123.123.123.123'
);

-- 화장실 상세정보 조회
SELECT *
FROM TOILET_DETAIL;

CREATE SEQUENCE KM.SQ_TOILET_DETAIL INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER;