-- 화장실 테이블 선언
create table TOILET_INFO (
	IDX NUMBER PRIMARY KEY,
	RESTROOM_NAME VARCHAR2(75) NOT NULL ,
	ADDRESS VARCHAR2(300) NOT NULL,
	DETAILED_ADDRESS VARCHAR2(300) NOT NULL,
	LONGITUDE NUMBER(30,15) NOT NULL, 
	LATITUDE NUMBER(30,15) NOT NULL,
	REVIEW_CNT NUMBER NOT NULL,
	SCORE_AVG NUMBER(3, 1) NOT NULL,
	INSERT_DT DATE NOT NULL, 
	UPDATE_DT DATE
);

-- 화장실 정보 등록
INSERT INTO TOILET_INFO(
	IDX,
	RESTROOM_NAME , 
	ADDRESS,
	DETAILED_ADDRESS,
	LONGITUDE,
	LATITUDE,
	REVIEW_CNT,
	SCORE_AVG,
	INSERT_DT
) 
VALUES(
	SQ_TOILET_INFO.NEXTVAL,
	'화장실 이름',
	'주소',
	'상세주소',
	127.12345678901234,
	36.12345678901234,
	5,
	4.1,
	sysdate
);

-- 화장실 정보 전체 조회
SELECT *
FROM TOILET_INFO;

DROP TABLE TOILET_INFO;

CREATE SEQUENCE KM.SQ_TOILET_INFO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER;-- ȭ��� ���̺� ����
create table TOILET_INFO (
	IDX NUMBER PRIMARY KEY,
	RESTROOM_NAME VARCHAR2(75) NOT NULL ,
	ADDRESS VARCHAR2(300) NOT NULL,
	DETAILED_ADDRESS VARCHAR2(300) NOT NULL,
	LONGITUDE NUMBER(30,15) NOT NULL, 
	LATITUDE NUMBER(30,15) NOT NULL,
	REVIEW_CNT NUMBER NOT NULL,
	SCORE_AVG NUMBER(3, 1) NOT NULL,
	INSERT_DT DATE NOT NULL, 
	UPDATE_DT DATE
);

-- ȭ��� ���� ���
INSERT INTO TOILET_INFO(
	IDX,
	RESTROOM_NAME , 
	ADDRESS,
	DETAILED_ADDRESS,
	LONGITUDE,
	LATITUDE,
	REVIEW_CNT,
	SCORE_AVG,
	INSERT_DT
) 
VALUES(
	SQ_TOILET_INFO.NEXTVAL,
	'ȭ��� �̸�',
	'�ּ�',
	'���ּ�',
	127.12345678901234,
	36.12345678901234,
	5,
	4.1,
	sysdate
);

-- ȭ��� ���� ��ü ��ȸ
SELECT *
FROM TOILET_INFO;

DROP TABLE TOILET_INFO;

CREATE SEQUENCE KM.SQ_TOILET_INFO INCREMENT BY 1 MINVALUE 1 NOCYCLE NOCACHE NOORDER;